Added CI/CD pipeline for UI-testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -75,57 +75,57 @@ jobs:
         name: allure-report-api
         path: ./api-testing/allure-report
 
-  # test-uis:
-  #   runs-on: ubuntu-latest
+  test-uis:
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #   - name: Checkout code
-  #     uses: actions/checkout@v4
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-  #   - name: Set up Node.js
-  #     uses: actions/setup-node@v4
-  #     with:
-  #       node-version: '20'
-  #       cache: 'npm'
-  #       cache-dependency-path: ./e2eui/package-lock.json
+    - name: Set up Node.js
+      uses: actions/setup-node@v4
+      with:
+        node-version: '22'
+        cache: 'npm'
+        cache-dependency-path: ./ui-testing/package-lock.json
 
-  #   - name: Cache Node.js modules
-  #     uses: actions/cache@v3
-  #     with:
-  #       path: ./e2eui/node_modules
-  #       key: ${{ runner.os }}-node-${{ hashFiles('e2eui/package-lock.json') }}
-  #       restore-keys: |
-  #         ${{ runner.os }}-node-
+    - name: Cache Node.js modules
+      uses: actions/cache@v3
+      with:
+        path: ./ui-testing/node_modules
+        key: ${{ runner.os }}-node-${{ hashFiles('ui-testing/package-lock.json') }}
+        restore-keys: |
+          ${{ runner.os }}-node-
 
-  #   - name: Install Node.js dependencies
-  #     working-directory: ./e2eui
-  #     run: npm ci
+    - name: Install Node.js dependencies
+      working-directory: ./ui-testing
+      run: npm ci
 
-  #   - name: Install Playwright Browsers
-  #     run: npx playwright install
+    - name: Install Playwright Browsers
+      working-directory: ./ui-testing
+      run: npx playwright install
 
-  #   - name: Install xvfb
-  #     run: sudo apt-get install -y xvfb
+    - name: Run API Tests Progress
+      working-directory: ./ui-testing
+      run: npm run test:progress || echo "Test failures ignored for pipeline continuation"
 
-  #   - name: Run Cucumber Tests & Generate Allure Results
-  #     working-directory: ./e2eui
-  #     run: xvfb-run npx cucumber-js npx cucumber-js
-  #     continue-on-error: true
+    - name: Run API Tests Allure
+      working-directory: ./ui-testing
+      run: npm run test:allure || echo "Test failures ignored for pipeline continuation"
 
-  #   - name: Generate Allure Report
-  #     working-directory: ./e2eui
-  #     run: npx allure generate allure-results --clean
+    - name: Generate Allure Report
+      working-directory: ./ui-testing
+      run: allure generate allure-results --clean
 
-  #   - name: Upload Allure Results as Artifact
-  #     uses: actions/upload-artifact@v3
-  #     with:
-  #       name: allure-report-ui
-  #       path: ./e2eui/allure-report
+    - name: Upload Allure Results as Artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: allure-report-ui
+        path: ./ui-testing/allure-report
  
   deploy-allure:
     runs-on: ubuntu-latest
-    # needs: [test-apis, test-uis]
-    needs: [test-apis]
+    needs: [test-apis, test-uis]
 
     steps:
     - name: Checkout code
@@ -137,24 +137,18 @@ jobs:
         name: allure-report-api
         path: allure-report-api
 
-    # - name: Download Allure UI Results Artifact
-    #   uses: actions/download-artifact@v3
-    #   with:
-    #     name: allure-report-ui
-    #     path: allure-report-ui
-
-
-    # - name: Prepare Deployment Directories
-    #   run: |
-    #     mkdir -p deployment/api-report
-    #     mkdir -p deployment/ui-report
-    #     cp -r allure-report-api/* deployment/api-report/
-    #     cp -r allure-report-ui/* deployment/ui-report/
+    - name: Download Allure UI Results Artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: allure-report-ui
+        path: allure-report-ui
 
     - name: Prepare Deployment Directories
       run: |
         mkdir -p deployment/api-report
+        mkdir -p deployment/ui-report
         cp -r allure-report-api/* deployment/api-report/
+        cp -r allure-report-ui/* deployment/ui-report/
 
     - name: Deploy Allure Reports to GitHub Pages
       uses: peaceiris/actions-gh-pages@v4
